---
paths:
  - "apps/frontend/src/**/*.{ts,tsx}"
---

## Frontend Conventions

- Runtime: Bun
- Preserve the router structure generated by the TanStack scaffold unless there is a deliberate product reason to change it
- Keep frontend imports inside the frontend workspace boundary
- Replace this seed rule with project-specific frontend guidance or delete it
